Python is slow so basically Numpy is used as replacement 10X faster than python
Plus vectorize operation rather than python
speed + features is offered 

In [4]:
import numpy as np 

In [5]:
print(np.__version__)

2.3.4


In [7]:
my_list = [1,2,3]
my_list = my_list  * 2
print(my_list)

[1, 2, 3, 1, 2, 3]


In [11]:
array = np.array([1,2,3])
array = array *2
print(array)
print(type(array))


[2 4 6]
<class 'numpy.ndarray'>


In [13]:
m_array = np.array('A')
print(m_array.ndim)

0


In [ ]:
m_array = np.array([['A','B','C'], ['D','E','F','G']])
print(m_array.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

for the numpy array to run it has be homogenous 

In [ ]:
n_array = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,'']],
                    [[1,2,3,4],[4,5,6,7],[7,8,9,'']],
                    [[1,2,3,4],[4,5,6,7],[7,8,9,'']],
                    [[1,2,3,4],[4,5,6,7],[7,8,9,'']],
                    [[1,2,3,4],[4,5,6,7],[7,8,9,'']]])
print(n_array.ndim)
print(n_array.shape)
print(n_array[0][0][0]) #This is called chain indexing
print(n_array[0,0,0]) # This is multidimensional indexing


3
(5, 3, 4)
1
1


In [ ]:
s_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                       [9, 10, 11, 12],
                         [13, 14 , 15, 16]])
print(s_array.shape)
# slicing example 
# array[start:end:step]

(4, 4)


In [23]:
print(s_array[0])
print(s_array[1])
print(s_array[3])
print(s_array[-2])

[1 2 3 4]
[5 6 7 8]
[13 14 15 16]
[ 9 10 11 12]


In [26]:
print(s_array[0:3]) # the ending index is exclusive
print(s_array[0:4:2])
print(s_array[::-1]) # the step can also be negative but output will be reversed

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
print(s_array[:, 1]) # for 2d it will be [row, column]
print(s_array[:, 0: 3]) 
print(s_array[:, 1:]) 


[ 2  6 10 14]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [30]:
print(s_array[0:2, 0:2]) # like selecting a quadrant specifies the row and the colund

[[1 2]
 [5 6]]


In [32]:
# vectorized math funcs 
array = np.array([1, 2, 3])
print(np.sqrt(array))
#different built in math function to apply to the whole arrays

[1.         1.41421356 1.73205081]


In [34]:
print(np.pi) # with built in constants too

3.141592653589793


In [35]:
radii = np.array([1, 2, 3])
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [36]:
# element-wise arithmetic
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 ** array2)

[5 7 9]
[  1  32 729]


In [39]:
#comparison operators
scores = np.array([91, 55, 100, 73, 82, 64])
print(scores == 100)
print(scores >= 60) # can create a boolean array 
scores[scores < 60]  = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[ 91   0 100  73  82  64]


Broadcasting allows Numpy to perform operations on arrays with different shapes by virtaully expanding dimensions
so they match the larger array's shape.

Possible only when
1. The dimensions have the same size.
2. One of the dimensions has a size of 1. 
basically fancy term for matrix multiplication

In [41]:
#broadcasting
import numpy as np
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)


(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


Aggregate functions = summarize data and typically return a single valueb

In [42]:
array = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))

55
5.5
2.8722813232690143


In [43]:
print(np.sum(array, axis=0))

[ 7  9 11 13 15]


In [44]:
print(np.sum(array, axis=1))

[15 40]


In [48]:
#filtering = Process of selecting elements from an array that match a given condition

ages = np.array([[21, 12, 19, 20, 16, 30, 18, 65],
                  [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18] # boolean indexing 
adults = ages[(ages >=18) & (ages < 65)]
print(adults)
print(teenagers)

[21 19 20 30 18 39 22 18 19 20 21]
[12 16 15]


In [ ]:
# where function to preserve the original shape but a lot slower than boolean indexing
adults2= np.where(ages >= 18, ages, 0)
print(adults2)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [51]:
#numpy to generate random numbers

rng = np.random.default_rng(seed=1) # seed to reproduce the same numbers

print(rng.integers(low=1, high=101, size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [52]:
#floating point number
print(np.random.uniform(low=-1, high=1))

-0.9665491145967497


other functions of random.default_rng() are .choice where an element from array will be given at random